#!/bin/bash

set -u 
set -e


# Skeleton script using the aws-cli. 
# This creates a VPC, 
# starts an EC2 instance in that VPC,  
# then creates an ELB and attach the instance. 
# Everything gets a tag. 

VPC_ID=$(aws ec2 create-vpc --cidr-block 192.168.0.0/16 --query Vpc.VpcId --output text)  

echo "Waiting for $VPC_ID"
aws ec2 wait vpc-available --vpc-ids $VPC_ID 
echo "$VPC_ID ready"

SUBNET_ID=$(aws ec2 create-subnet --vpc-id $VPC_ID --availability-zone us-east-1a \
    --cidr-block 192.168.1.0/24 --query Subnet.SubnetId --output text) 

aws ec2 wait subnet-available --subnet-ids $SUBNET_ID 
echo "$SUBNET_ID created" 

GW=$(aws ec2 create-internet-gateway --query InternetGateway.InternetGatewayId --output text)

aws ec2 attach-internet-gateway --internet-gateway-id $GW --vpc-id $VPC_ID

ROUTE_ID=$(aws ec2 describe-route-tables \ 
    --filters Name=vpc-id,Values=$VPC_ID --output text --query 'RouteTables[].RouteTableId')

aws ec2 associate-route-table --subnet-id $SUBNET_ID --route-table-id $ROUTE_ID
aws ec2 create-route --route-table-id $ROUTE_ID --gateway-id $GW --destination-cidr-block 0.0.0.0/0

SECURITY_GROUP=$(aws ec2 create-security-group --group-name "Auto" --description "Auto generated" \ 
    --vpc-id $VPC_ID --query GroupId --output text) 
aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP --protocol tcp --port 22 --cidr 0.0.0.0/0

ELB_ID=$(aws elb create-load-balancer --load-balancer-name TEST \ 
    --listeners "Protocol=HTTP,LoadBalancerPort=80,InstanceProtocol=HTTP,InstancePort=80" --subnets $SUBNET_ID --security-groups $SECURITY_GROUP)

# --placement AvailabilityZone=value,GroupName=value,Tenancy=value
INSTANCE_ID=$(aws ec2 run-instances --image-id ami-d85e75b0 --count 1 --instance-type t1.micro --placement AvailabilityZone=us-east-1a \ 
    --key-name 06_17 --security-group-ids $SECURITY_GROUP --subnet-id $SUBNET_ID --associate-public-ip-address\
    --query Instances[].InstanceId --output text) 

echo "Waiting for $INSTANCE_ID"
aws ec2 wait instance-running --instance-ids $INSTANCE_ID  
echo "$INSTANCE_ID ready"

aws ec2 create-tags --resources $VPC_ID $SUBNET_ID $SECURITY_GROUP $INSTANCE_ID --tags Key=Name,Value=Autogenerated 

aws elb register-instances-with-load-balancer --load-balancer-name TEST --instances $INSTANCE_ID
echo "All done"
